CREATE TABLE APP_CUENTA.DW_AL_CUENTA
(
  DWACCUENTAID      NUMBER(10)                  NOT NULL,
  DWACNUMCUENTA     VARCHAR2(16 BYTE)           NOT NULL,
  DWACFECHACREADO   DATE                        NOT NULL,
  DWACCLIENTEID     VARCHAR2(512 BYTE)          NOT NULL,
  DWCACATEGORIAID   NUMBER(10)                  NOT NULL,
  DWATTIPOCUENTAID  NUMBER(10)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_AL_DESEMBOLSO
(
  DWDIDESEMBOLSOID  NUMBER(10)                  NOT NULL,
  DWACCUENTAID      NUMBER(10)                  NOT NULL,
  DWDIIFACTURAID    NUMBER(10)                  NOT NULL,
  DWDIDESCRIPCION   VARCHAR2(512 BYTE)          NOT NULL,
  DWDINUMCUOTA      NUMBER(2)                   NOT NULL,
  DWDIFECHACREADO   DATE                        NOT NULL,
  DWUSCODIGO        NUMBER(10)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_AL_DOCUMENTO
(
  DWDIDESEMBOLSOID     NUMBER(10)               NOT NULL,
  DWACCUENTAID         NUMBER(10)               NOT NULL,
  DWDTTIPODOCUMENTOID  NUMBER(10)               NOT NULL,
  DWDCDOCUMENTOID      NUMBER(10)               NOT NULL,
  DWDCFECHACREADO      DATE                     NOT NULL,
  DWDCMONTO            NUMBER(10,2)             NOT NULL,
  DWDCDESCRIPCION      VARCHAR2(4000 BYTE)      NOT NULL,
  DWUSCODIGO           NUMBER(10)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_AL_ESTADO_CUENTA
(
  DWASESTADOID      NUMBER(10)                  NOT NULL,
  DWACCUENTAID      NUMBER(10)                  NOT NULL,
  DWASFECHAEMISION  DATE                        NOT NULL,
  DWASFECHAPAGO     DATE                        NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_AL_SOLICITUD
(
  DWRESOLICITUDID     NUMBER(10)                NOT NULL,
  DWRECLIENTEID       NUMBER(10)                NOT NULL,
  DWRENIT             VARCHAR2(10 BYTE)         NOT NULL,
  DWREINGRESOMENSUAL  NUMBER(10,2)              NOT NULL,
  DWSRESTADOID        NUMBER(10)                NOT NULL,
  DWUSCODIGO          NUMBER(10)                NOT NULL,
  DWREFECHA           DATE                      NOT NULL,
  DWREMOTIVO          VARCHAR2(256 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_CAT_CATEGORIA
(
  DWCACATEGORIAID    NUMBER(10)                 NOT NULL,
  DWCADESCRIPCION    VARCHAR2(1024 BYTE)        NOT NULL,
  DWCACREDITOMAXIMO  NUMBER(10,2)               NOT NULL,
  DWCACREDITOMINIMO  NUMBER(10,2)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_CAT_ESTADO_SOLICITUD
(
  DWSRESTADOID     NUMBER(10)                   NOT NULL,
  DWSRDESCRIPCION  VARCHAR2(128 BYTE)           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_CAT_TIPO_CUENTA
(
  DWATTIPOCUENTAID  NUMBER(10)                  NOT NULL,
  DWATDESCRIPCION   VARCHAR2(1024 BYTE)         NOT NULL,
  DWATINTERES       NUMBER(10)                  NOT NULL,
  DWATFECHACORTE    DATE                        NOT NULL,
  DWATFECHALIMITE   VARCHAR2(32 BYTE)           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_CAT_TIPO_DOCUMENTO
(
  DWDTTIPODOCUMENTOID  NUMBER(10)               NOT NULL,
  DWDTDESCRIPCION      VARCHAR2(256 BYTE)       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_PAR_PARAMETROS
(
  DWPAPARAMETROID      NUMBER(10)               NOT NULL,
  DWPANOMBREPARAMETRO  VARCHAR2(128 BYTE)       NOT NULL,
  DWPADESCRIPCION      VARCHAR2(256 BYTE)       NOT NULL,
  DWPAFECHACREADO      DATE                     NOT NULL,
  DWPAUSUARIO          VARCHAR2(64 BYTE)        NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_PE_PERSONA
(
  DWPEPERSONAID        NUMBER(10)               NOT NULL,
  DWPEPRIMERNOMBRE     VARCHAR2(128 BYTE)       NOT NULL,
  DWPESEGUNDONOMBRE    VARCHAR2(128 BYTE),
  DWPETERCERNOMBRE     VARCHAR2(128 BYTE),
  DWPEPRIMERAPELLIDO   VARCHAR2(128 BYTE)       NOT NULL,
  DWPESEGUNDOAPELLIDO  VARCHAR2(128 BYTE),
  DWPEAPELLIDOCASADA   VARCHAR2(128 BYTE),
  DWPECORREO           VARCHAR2(128 BYTE)       NOT NULL,
  DWPETELEFONO         NUMBER(8)                NOT NULL,
  DWPEFECHACREADO      DATE                     NOT NULL,
  DIRECCION            VARCHAR2(256 BYTE),
  CODIGO               VARCHAR2(32 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_PERMISO_ASOC
(
  DWPMPERMISOID  NUMBER(10)                     NOT NULL,
  DWPFPERFILID   NUMBER(10)                     NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_PF_PERFIL
(
  DWPFPERFILID     NUMBER(10)                   NOT NULL,
  DWPFNOMBRE       VARCHAR2(128 BYTE)           NOT NULL,
  DWPFFECHACREADO  DATE                         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_PM_PERMISO
(
  DWPMPERMISOID      NUMBER(10)                 NOT NULL,
  DWPMNOMBRE         VARCHAR2(128 BYTE)         NOT NULL,
  DWPMNOMBRETECNICO  VARCHAR2(128 BYTE)         NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_TC_TARJETA
(
  NUMERO_TARJETA    NUMBER(32)                  NOT NULL,
  NOMBRE_TARJETA    VARCHAR2(256 BYTE)          NOT NULL,
  CODIGO_SEGURIDAD  VARCHAR2(16 BYTE)           NOT NULL,
  MES_VENCIMIENTO   NUMBER(4)                   NOT NULL,
  ANIO_VENCIMIENTO  NUMBER(4)                   NOT NULL,
  NIT_CLIENTE       VARCHAR2(64 BYTE)           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE APP_CUENTA.DW_US_USUARIO
(
  DWUSCODIGO       NUMBER(10)                   NOT NULL,
  DWUSUSUARIOID    VARCHAR2(128 BYTE)           NOT NULL,
  DWUSPASSWORD     VARCHAR2(256 BYTE)           NOT NULL,
  DWUSFECHACREADO  DATE                         NOT NULL,
  DWPEPERSONAID    NUMBER(10)                   NOT NULL,
  DWPFPERFILID     NUMBER(10)                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX APP_CUENTA.CATEGORIAPK01 ON APP_CUENTA.DW_CAT_CATEGORIA
(DWCACATEGORIAID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.CUENTAPK01 ON APP_CUENTA.DW_AL_CUENTA
(DWACCUENTAID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.DESEMBOLSOPK01 ON APP_CUENTA.DW_AL_DESEMBOLSO
(DWDIDESEMBOLSOID, DWACCUENTAID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.DOCUMENTOPK01 ON APP_CUENTA.DW_AL_DOCUMENTO
(DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.DWALCUENTAIDX01 ON APP_CUENTA.DW_AL_CUENTA
(DWACCLIENTEID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.DWTCTARJETAPK01 ON APP_CUENTA.DW_TC_TARJETA
(NIT_CLIENTE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.DWTCTARJETAUK01 ON APP_CUENTA.DW_TC_TARJETA
(NUMERO_TARJETA)
LOGGING
NOPARALLEL;


CREATE INDEX APP_CUENTA.DWUSUARIOIDX01 ON APP_CUENTA.DW_US_USUARIO
(DWPEPERSONAID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.ESTADOCUENTAPK01 ON APP_CUENTA.DW_AL_ESTADO_CUENTA
(DWASESTADOID, DWACCUENTAID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.ESTADOSOLICITUDPK01 ON APP_CUENTA.DW_CAT_ESTADO_SOLICITUD
(DWSRESTADOID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.PARAMETROSPK01 ON APP_CUENTA.DW_PAR_PARAMETROS
(DWPAPARAMETROID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.PERFILPK01 ON APP_CUENTA.DW_PF_PERFIL
(DWPFPERFILID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.PERSONAPK01 ON APP_CUENTA.DW_PE_PERSONA
(DWPEPERSONAID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.PK16 ON APP_CUENTA.DW_PM_PERMISO
(DWPMPERMISOID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.SOLICITUDPK01 ON APP_CUENTA.DW_AL_SOLICITUD
(DWRESOLICITUDID)
LOGGING
NOPARALLEL;


--  There is no statement for index APP_CUENTA.SYS_C007507.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX APP_CUENTA.TIPOCUENTAPK01 ON APP_CUENTA.DW_CAT_TIPO_CUENTA
(DWATTIPOCUENTAID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.TIPODOCUMENTOPK01 ON APP_CUENTA.DW_CAT_TIPO_DOCUMENTO
(DWDTTIPODOCUMENTOID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX APP_CUENTA.USUARIOPK01 ON APP_CUENTA.DW_US_USUARIO
(DWUSCODIGO)
LOGGING
NOPARALLEL;


ALTER TABLE APP_CUENTA.DW_AL_CUENTA ADD (
  CONSTRAINT CUENTAPK01
  PRIMARY KEY
  (DWACCUENTAID)
  USING INDEX APP_CUENTA.CUENTAPK01
  ENABLE VALIDATE,
  UNIQUE (DWACNUMCUENTA)
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_DESEMBOLSO ADD (
  CONSTRAINT DESEMBOLSOPK01
  PRIMARY KEY
  (DWDIDESEMBOLSOID, DWACCUENTAID)
  USING INDEX APP_CUENTA.DESEMBOLSOPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_DOCUMENTO ADD (
  CONSTRAINT DOCUMENTOPK01
  PRIMARY KEY
  (DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID)
  USING INDEX APP_CUENTA.DOCUMENTOPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_ESTADO_CUENTA ADD (
  CONSTRAINT ESTADOCUENTAPK01
  PRIMARY KEY
  (DWASESTADOID, DWACCUENTAID)
  USING INDEX APP_CUENTA.ESTADOCUENTAPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_SOLICITUD ADD (
  CONSTRAINT SOLICITUDPK01
  PRIMARY KEY
  (DWRESOLICITUDID)
  USING INDEX APP_CUENTA.SOLICITUDPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_CAT_CATEGORIA ADD (
  CONSTRAINT CATEGORIAPK01
  PRIMARY KEY
  (DWCACATEGORIAID)
  USING INDEX APP_CUENTA.CATEGORIAPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_CAT_ESTADO_SOLICITUD ADD (
  CONSTRAINT ESTADOSOLICITUDPK01
  PRIMARY KEY
  (DWSRESTADOID)
  USING INDEX APP_CUENTA.ESTADOSOLICITUDPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_CAT_TIPO_CUENTA ADD (
  CONSTRAINT TIPOCUENTAPK01
  PRIMARY KEY
  (DWATTIPOCUENTAID)
  USING INDEX APP_CUENTA.TIPOCUENTAPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_CAT_TIPO_DOCUMENTO ADD (
  CONSTRAINT TIPODOCUMENTOPK01
  PRIMARY KEY
  (DWDTTIPODOCUMENTOID)
  USING INDEX APP_CUENTA.TIPODOCUMENTOPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_PAR_PARAMETROS ADD (
  CONSTRAINT PARAMETROSPK01
  PRIMARY KEY
  (DWPAPARAMETROID)
  USING INDEX APP_CUENTA.PARAMETROSPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_PE_PERSONA ADD (
  CONSTRAINT PERSONAPK01
  PRIMARY KEY
  (DWPEPERSONAID)
  USING INDEX APP_CUENTA.PERSONAPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_PF_PERFIL ADD (
  CONSTRAINT PERFILPK01
  PRIMARY KEY
  (DWPFPERFILID)
  USING INDEX APP_CUENTA.PERFILPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_PM_PERMISO ADD (
  CONSTRAINT PK16
  PRIMARY KEY
  (DWPMPERMISOID)
  USING INDEX APP_CUENTA.PK16
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_TC_TARJETA ADD (
  CONSTRAINT DWTCTARJETAPK01
  PRIMARY KEY
  (NIT_CLIENTE)
  USING INDEX APP_CUENTA.DWTCTARJETAPK01
  ENABLE VALIDATE,
  CONSTRAINT DWTCTARJETAUK01
  UNIQUE (NUMERO_TARJETA)
  USING INDEX APP_CUENTA.DWTCTARJETAUK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_US_USUARIO ADD (
  CONSTRAINT USUARIOPK01
  PRIMARY KEY
  (DWUSCODIGO)
  USING INDEX APP_CUENTA.USUARIOPK01
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_CUENTA ADD (
  CONSTRAINT REFDW_CAT_CATEGORIA11 
  FOREIGN KEY (DWCACATEGORIAID) 
  REFERENCES APP_CUENTA.DW_CAT_CATEGORIA (DWCACATEGORIAID)
  ENABLE VALIDATE,
  CONSTRAINT REFDW_CAT_TIPO_CUENTA21 
  FOREIGN KEY (DWATTIPOCUENTAID) 
  REFERENCES APP_CUENTA.DW_CAT_TIPO_CUENTA (DWATTIPOCUENTAID)
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_DESEMBOLSO ADD (
  CONSTRAINT REFDW_AL_CUENTA41 
  FOREIGN KEY (DWACCUENTAID) 
  REFERENCES APP_CUENTA.DW_AL_CUENTA (DWACCUENTAID)
  ENABLE VALIDATE,
  CONSTRAINT REFDW_US_USUARIO191 
  FOREIGN KEY (DWUSCODIGO) 
  REFERENCES APP_CUENTA.DW_US_USUARIO (DWUSCODIGO)
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_DOCUMENTO ADD (
  CONSTRAINT REFDW_AL_DESEMBOLSO131 
  FOREIGN KEY (DWDIDESEMBOLSOID, DWACCUENTAID) 
  REFERENCES APP_CUENTA.DW_AL_DESEMBOLSO (DWDIDESEMBOLSOID,DWACCUENTAID)
  ENABLE VALIDATE,
  CONSTRAINT REFDW_CAT_TIPO_DOCUMENTO141 
  FOREIGN KEY (DWDTTIPODOCUMENTOID) 
  REFERENCES APP_CUENTA.DW_CAT_TIPO_DOCUMENTO (DWDTTIPODOCUMENTOID)
  ENABLE VALIDATE,
  CONSTRAINT REFDW_US_USUARIO201 
  FOREIGN KEY (DWUSCODIGO) 
  REFERENCES APP_CUENTA.DW_US_USUARIO (DWUSCODIGO)
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_ESTADO_CUENTA ADD (
  CONSTRAINT REFDW_AL_CUENTA51 
  FOREIGN KEY (DWACCUENTAID) 
  REFERENCES APP_CUENTA.DW_AL_CUENTA (DWACCUENTAID)
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_AL_SOLICITUD ADD (
  CONSTRAINT REFDW_CAT_ESTADO_SOLICITUD61 
  FOREIGN KEY (DWSRESTADOID) 
  REFERENCES APP_CUENTA.DW_CAT_ESTADO_SOLICITUD (DWSRESTADOID)
  ENABLE VALIDATE,
  CONSTRAINT REFDW_US_USUARIO151 
  FOREIGN KEY (DWUSCODIGO) 
  REFERENCES APP_CUENTA.DW_US_USUARIO (DWUSCODIGO)
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_PERMISO_ASOC ADD (
  CONSTRAINT REFDW_PF_PERFIL22 
  FOREIGN KEY (DWPFPERFILID) 
  REFERENCES APP_CUENTA.DW_PF_PERFIL (DWPFPERFILID)
  ENABLE VALIDATE,
  CONSTRAINT REFDW_PM_PERMISO21 
  FOREIGN KEY (DWPMPERMISOID) 
  REFERENCES APP_CUENTA.DW_PM_PERMISO (DWPMPERMISOID)
  ENABLE VALIDATE);

ALTER TABLE APP_CUENTA.DW_US_USUARIO ADD (
  CONSTRAINT REFDW_PE_PERSONA161 
  FOREIGN KEY (DWPEPERSONAID) 
  REFERENCES APP_CUENTA.DW_PE_PERSONA (DWPEPERSONAID)
  ENABLE VALIDATE,
  CONSTRAINT REFDW_PF_PERFIL181 
  FOREIGN KEY (DWPFPERFILID) 
  REFERENCES APP_CUENTA.DW_PF_PERFIL (DWPFPERFILID)
  ENABLE VALIDATE);
Insert into APP_CUENTA.DW_AL_CUENTA
   (DWACCUENTAID, DWACNUMCUENTA, DWACFECHACREADO, DWACCLIENTEID, DWCACATEGORIAID, 
    DWATTIPOCUENTAID)
 Values
   (0, '445566998856', TO_DATE('11/03/2017 22:54:49', 'MM/DD/YYYY HH24:MI:SS'), '0', 1, 
    2);
COMMIT;

Insert into APP_CUENTA.DW_AL_DESEMBOLSO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDIIFACTURAID, DWDIDESCRIPCION, DWDINUMCUOTA, 
    DWDIFECHACREADO, DWUSCODIGO)
 Values
   (0, 0, 0, 'COMPRA', 10, 
    TO_DATE('11/04/2017 08:30:47', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into APP_CUENTA.DW_AL_DESEMBOLSO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDIIFACTURAID, DWDIDESCRIPCION, DWDINUMCUOTA, 
    DWDIFECHACREADO, DWUSCODIGO)
 Values
   (1, 0, 1, 'COMPRA', 6, 
    TO_DATE('11/05/2017 17:33:54', 'MM/DD/YYYY HH24:MI:SS'), 0);
Insert into APP_CUENTA.DW_AL_DESEMBOLSO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDIIFACTURAID, DWDIDESCRIPCION, DWDINUMCUOTA, 
    DWDIFECHACREADO, DWUSCODIGO)
 Values
   (2, 0, 2, 'COMPRA', 10, 
    TO_DATE('11/05/2017 22:46:32', 'MM/DD/YYYY HH24:MI:SS'), 0);
COMMIT;

Insert into APP_CUENTA.DW_AL_DOCUMENTO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID, DWDCFECHACREADO, 
    DWDCMONTO, DWDCDESCRIPCION, DWUSCODIGO)
 Values
   (0, 0, 1, 0, TO_DATE('11/04/2017 08:31:28', 'MM/DD/YYYY HH24:MI:SS'), 
    1000, 'COMPRA', 0);
Insert into APP_CUENTA.DW_AL_DOCUMENTO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID, DWDCFECHACREADO, 
    DWDCMONTO, DWDCDESCRIPCION, DWUSCODIGO)
 Values
   (0, 0, 2, 0, TO_DATE('11/04/2017 08:32:00', 'MM/DD/YYYY HH24:MI:SS'), 
    -100, 'PAGO', 0);
Insert into APP_CUENTA.DW_AL_DOCUMENTO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID, DWDCFECHACREADO, 
    DWDCMONTO, DWDCDESCRIPCION, DWUSCODIGO)
 Values
   (0, 0, 2, 1, TO_DATE('11/05/2017 17:41:02', 'MM/DD/YYYY HH24:MI:SS'), 
    -100, 'PAGO', 0);
Insert into APP_CUENTA.DW_AL_DOCUMENTO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID, DWDCFECHACREADO, 
    DWDCMONTO, DWDCDESCRIPCION, DWUSCODIGO)
 Values
   (0, 0, 2, 2, TO_DATE('11/05/2017 18:12:46', 'MM/DD/YYYY HH24:MI:SS'), 
    -100, 'PAGO FACTURA', 0);
Insert into APP_CUENTA.DW_AL_DOCUMENTO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID, DWDCFECHACREADO, 
    DWDCMONTO, DWDCDESCRIPCION, DWUSCODIGO)
 Values
   (0, 0, 2, 3, TO_DATE('11/05/2017 22:45:36', 'MM/DD/YYYY HH24:MI:SS'), 
    -700, 'PAGO', 0);
Insert into APP_CUENTA.DW_AL_DOCUMENTO
   (DWDIDESEMBOLSOID, DWACCUENTAID, DWDTTIPODOCUMENTOID, DWDCDOCUMENTOID, DWDCFECHACREADO, 
    DWDCMONTO, DWDCDESCRIPCION, DWUSCODIGO)
 Values
   (2, 0, 1, 1, TO_DATE('11/05/2017 22:46:32', 'MM/DD/YYYY HH24:MI:SS'), 
    -1500, 'COMPRA', 0);
COMMIT;

Insert into APP_CUENTA.DW_CAT_CATEGORIA
   (DWCACATEGORIAID, DWCADESCRIPCION, DWCACREDITOMAXIMO, DWCACREDITOMINIMO)
 Values
   (1, 'Serie A', 10000, 5000);
Insert into APP_CUENTA.DW_CAT_CATEGORIA
   (DWCACATEGORIAID, DWCADESCRIPCION, DWCACREDITOMAXIMO, DWCACREDITOMINIMO)
 Values
   (2, 'Serie B', 12000, 6000);
COMMIT;

Insert into APP_CUENTA.DW_CAT_ESTADO_SOLICITUD
   (DWSRESTADOID, DWSRDESCRIPCION)
 Values
   (1, 'Ingresada');
Insert into APP_CUENTA.DW_CAT_ESTADO_SOLICITUD
   (DWSRESTADOID, DWSRDESCRIPCION)
 Values
   (2, 'Atendiendo');
Insert into APP_CUENTA.DW_CAT_ESTADO_SOLICITUD
   (DWSRESTADOID, DWSRDESCRIPCION)
 Values
   (3, 'Aprobada');
Insert into APP_CUENTA.DW_CAT_ESTADO_SOLICITUD
   (DWSRESTADOID, DWSRDESCRIPCION)
 Values
   (4, 'Rechazada');
COMMIT;

Insert into APP_CUENTA.DW_CAT_TIPO_CUENTA
   (DWATTIPOCUENTAID, DWATDESCRIPCION, DWATINTERES, DWATFECHACORTE, DWATFECHALIMITE)
 Values
   (2, 'Cliente Oro', 4, TO_DATE('01/14/2150 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '20');
Insert into APP_CUENTA.DW_CAT_TIPO_CUENTA
   (DWATTIPOCUENTAID, DWATDESCRIPCION, DWATINTERES, DWATFECHACORTE, DWATFECHALIMITE)
 Values
   (3, 'Cliente Plata', 6, TO_DATE('01/10/2150 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), '28');
COMMIT;

Insert into APP_CUENTA.DW_CAT_TIPO_DOCUMENTO
   (DWDTTIPODOCUMENTOID, DWDTDESCRIPCION)
 Values
   (1, 'Nota de Credito');
Insert into APP_CUENTA.DW_CAT_TIPO_DOCUMENTO
   (DWDTTIPODOCUMENTOID, DWDTDESCRIPCION)
 Values
   (2, 'Nota de Debito');
COMMIT;

Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (1, 'CLIENTE', 'Cliente Prueba', TO_DATE('11/01/2017 21:29:41', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (2, 'DPI', '1234567890610', TO_DATE('11/01/2017 21:30:15', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (3, 'NIT', '5555633-9', TO_DATE('11/01/2017 21:30:32', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (4, 'CLIENTEID', '1', TO_DATE('11/01/2017 23:24:56', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (5, 'DIRECCION', '2 Avenida 11-77 Zona 1', TO_DATE('11/03/2017 22:52:58', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (6, 'TELEFONO', '55557788', TO_DATE('11/03/2017 22:53:18', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (7, 'PATHLOG_WS', '/logs/SistemaCuentaWs.log', TO_DATE('11/03/2017 22:53:59', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
Insert into APP_CUENTA.DW_PAR_PARAMETROS
   (DWPAPARAMETROID, DWPANOMBREPARAMETRO, DWPADESCRIPCION, DWPAFECHACREADO, DWPAUSUARIO)
 Values
   (8, 'ENDPOINT_VALIDATARJETA', 'http://52.177.194.230:8080/tcws/ValidaMonto?wsdl', TO_DATE('11/10/2017 00:14:59', 'MM/DD/YYYY HH24:MI:SS'), 'ADMIN');
COMMIT;

Insert into APP_CUENTA.DW_PERMISO_ASOC
   (DWPMPERMISOID, DWPFPERFILID)
 Values
   (3, 2);
COMMIT;

Insert into APP_CUENTA.DW_PE_PERSONA
   (DWPEPERSONAID, DWPEPRIMERNOMBRE, DWPESEGUNDONOMBRE, DWPETERCERNOMBRE, DWPEPRIMERAPELLIDO, 
    DWPESEGUNDOAPELLIDO, DWPEAPELLIDOCASADA, DWPECORREO, DWPETELEFONO, DWPEFECHACREADO, 
    DIRECCION, CODIGO)
 Values
   (1, 'Usuario', NULL, NULL, 'Service', 
    NULL, NULL, 'user.service', 52165091, TO_DATE('10/25/2017 22:56:58', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into APP_CUENTA.DW_PE_PERSONA
   (DWPEPERSONAID, DWPEPRIMERNOMBRE, DWPESEGUNDONOMBRE, DWPETERCERNOMBRE, DWPEPRIMERAPELLIDO, 
    DWPESEGUNDOAPELLIDO, DWPEAPELLIDOCASADA, DWPECORREO, DWPETELEFONO, DWPEFECHACREADO, 
    DIRECCION, CODIGO)
 Values
   (0, 'Usuario', NULL, NULL, 'Service', 
    NULL, NULL, 'user.service', 52165091, TO_DATE('11/05/2017 23:02:43', 'MM/DD/YYYY HH24:MI:SS'), 
    NULL, NULL);
Insert into APP_CUENTA.DW_PE_PERSONA
   (DWPEPERSONAID, DWPEPRIMERNOMBRE, DWPESEGUNDONOMBRE, DWPETERCERNOMBRE, DWPEPRIMERAPELLIDO, 
    DWPESEGUNDOAPELLIDO, DWPEAPELLIDOCASADA, DWPECORREO, DWPETELEFONO, DWPEFECHACREADO, 
    DIRECCION, CODIGO)
 Values
   (10000, 'Cliente', 'Testeo', NULL, 'Prueba', 
    NULL, NULL, 'cliente.prueba@gmail.com', 46352487, TO_DATE('11/09/2017 22:10:05', 'MM/DD/YYYY HH24:MI:SS'), 
    'Guatemala', '0');
COMMIT;

Insert into APP_CUENTA.DW_PF_PERFIL
   (DWPFPERFILID, DWPFNOMBRE, DWPFFECHACREADO)
 Values
   (2, 'QA', TO_DATE('10/25/2017 22:07:46', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;

Insert into APP_CUENTA.DW_PM_PERMISO
   (DWPMPERMISOID, DWPMNOMBRE, DWPMNOMBRETECNICO)
 Values
   (1, 'Menu Cuenta', 'mncAccount');
Insert into APP_CUENTA.DW_PM_PERMISO
   (DWPMPERMISOID, DWPMNOMBRE, DWPMNOMBRETECNICO)
 Values
   (2, 'Menu Credito', 'mncCreditos');
Insert into APP_CUENTA.DW_PM_PERMISO
   (DWPMPERMISOID, DWPMNOMBRE, DWPMNOMBRETECNICO)
 Values
   (3, 'Menu Mantenimientos', 'mncMant');
Insert into APP_CUENTA.DW_PM_PERMISO
   (DWPMPERMISOID, DWPMNOMBRE, DWPMNOMBRETECNICO)
 Values
   (4, 'Menu Pagos', 'mncPago');
Insert into APP_CUENTA.DW_PM_PERMISO
   (DWPMPERMISOID, DWPMNOMBRE, DWPMNOMBRETECNICO)
 Values
   (5, 'Menu Reporte Cuentas', 'mncRepCuenta');
Insert into APP_CUENTA.DW_PM_PERMISO
   (DWPMPERMISOID, DWPMNOMBRE, DWPMNOMBRETECNICO)
 Values
   (6, 'Menu Admon Usuarios', 'mncConfUser');
COMMIT;

Insert into APP_CUENTA.DW_US_USUARIO
   (DWUSCODIGO, DWUSUSUARIOID, DWUSPASSWORD, DWUSFECHACREADO, DWPEPERSONAID, 
    DWPFPERFILID)
 Values
   (1, 'ottoniel.molina', 'molina123', TO_DATE('10/25/2017 22:57:23', 'MM/DD/YYYY HH24:MI:SS'), 1, 
    2);
Insert into APP_CUENTA.DW_US_USUARIO
   (DWUSCODIGO, DWUSUSUARIOID, DWUSPASSWORD, DWUSFECHACREADO, DWPEPERSONAID, 
    DWPFPERFILID)
 Values
   (0, 'admin', 'admin', TO_DATE('11/01/2017 22:53:19', 'MM/DD/YYYY HH24:MI:SS'), 0, 
    2);
COMMIT;
